In [ ]:
import numpy as np
import pygame
import sys
import random
import sys
wind = pygame.display.set_mode((600,600))
pygame.init()
def create_board():
    array = np.zeros((4,4))
    for no in range(2):
        x1 = np.random.randint(0,4,1)
        y1 = np.random.randint(0,4,1)
        array[x1,y1] = 2
    #array[0][1] = 2
    #array[1][1] = 2
    #array[3][1] = 2
    return array
array = create_board()
print(array)
def add_new(direction):
    new = False
    new_number = random.choice([2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0])
    while new == False:
        if direction == "right":
            y = np.random.randint(0,4)
            x = random.choice([3,2,2,1,1,1,0,0,0,0])
        if direction == "left":
            y = np.random.randint(0,4)
            x = random.choice([0,1,1,2,2,2,3,3,3,3])
        if direction == "down":
            y = np.random.randint(0,4)
            x = random.choice([3,2,2,1,1,1,0,0,0,0])
        if direction == "up":
            x = np.random.randint(0,4)
            y = random.choice([0,1,1,2,2,2,3,3,3,3])
        if array[y][x] == 0:
            array[y][x] = new_number
            new = True
    return array
def move_right():
    possible = False
    for i in range(4):
        j = 3
        for ii in range(4):
            ii = 3-ii
            if array[i][ii] != 0:
                stop = "no"
                for adjacent in range(ii):
                    adjacent = ii - adjacent
                    if array[i][adjacent-1] != 0 and stop == "no":
                        if array[i][ii] == array[i][adjacent-1]:
                            array[i][ii] *= 2
                            array[i][adjacent-1] = 0
                            stop = "yes"
                            possible = True
#for right
                        else:
                            stop = "yes"
                array[i][j] = array[i][ii]
                if ii != j:
                    array[i][ii] = 0
                    possible = True
                j -= 1
    if possible == True:
        add_new("right")
    return array
def move_left():
    possible = False
    for i in range(4):
        j = 0
        for ii in range(4):
            if array[i][ii] != 0:
                stop = "no"
                for adjacent in range(3-ii):
                    adjacent = ii + adjacent
                    if array[i][adjacent+1] != 0 and stop == "no":
                        if array[i][ii] == array[i][adjacent+1]:
                            array[i][ii] *= 2
                            array[i][adjacent+1] = 0
                            stop = "yes"
                            possible = True
#for left
                        else:
                            stop = "yes"
                array[i][j] = array[i][ii]
                if ii != j:
                    array[i][ii] = 0
                    possible = True
                j += 1
    if possible == True:
        
        add_new("right")
    return array
def move_down():
    possible = False
    for i in range(4):
        j = 3
        for ii in range(4):
            ii = 3-ii
            if array[ii][i] != 0:                
                stop = "no"
                if ii != 0:
                    for adjacent in range(ii):
                        adjacent = ii - adjacent
                        if array[adjacent-1][i] != 0 and stop == "no":
                            if array[ii][i] == array[adjacent-1][i]:
                                array[ii][i] *= 2
                                array[adjacent-1][i] = 0
                                stop = "yes"
                                possible = True
    #for down #for down #for down #for down #for down #for down#for down #for down
                            else:
                                stop = "yes"
                array[j][i] = array[ii][i]
                if ii != j:
                    array[ii][i] = 0
                    possible = True
                j -= 1
    if possible == True:
        add_new("down")
    return array
def move_up():
    possible = False
    for i in range(4):
        j = 0
        for ii in range(4):
            if array[ii][i] != 0:
                stop = "no"
                if ii != 3:
                    for adjacent in range(3-ii):
                        adjacent = ii + adjacent
                        if array[adjacent+1][i] != 0 and stop == "no":
                            if array[ii][i] == array[adjacent+1][i]:
                                array[ii][i] *= 2
                                array[adjacent+1][i] = 0
                                stop = "yes"
                                possible = True
    #for up
                            else:
                                stop = "yes"
                array[j][i] = array[ii][i]
                if ii != j:
                    array[ii][i] = 0
                    possible = True
                j += 1
    if possible == True:
        add_new("up")
    return array
btnsize = 150
myfont = pygame.font.SysFont("monospace",74)
def get_board(array):
    for c in range(4):
        for r in range(4):
            if array[c][r] <= 64 and array[c][r] > 0:
                pygame.draw.rect(wind,(255,255-(array[c][r]*4 -1),255- (array[c][r]*4 -1)),(r*btnsize,c*btnsize,btnsize-5,btnsize-5))
            elif array[c][r] > 64 and array[c][r] <= 1024:
                pygame.draw.rect(wind,(255,255,255- (array[c][r]/4 -1)),(r*btnsize,c*btnsize,btnsize-5,btnsize-5))
            elif array[c][r] == 2048:
                pygame.draw.rect(wind,(0,0,0),(r*btnsize,c*btnsize,btnsize-5,btnsize-5))
            else:
                pygame.draw.rect(wind,(192,192,192),(r*btnsize,c*btnsize,btnsize-5,btnsize-5))
            if array[c][r] != 0:
                label = myfont.render(str(int(array[c][r])),1,(0,0,255))
                wind.blit(label,(r*btnsize,c*btnsize+25))
    pygame.display.update()
def check_win(array):
    for c in range(4):
        for r in range(4):
            if array[c][r] == 2048:
                pygame.display.set_caption("YOU WON. YOU MADE 2048")
                pygame.time.wait(2000)
                sys.exit()
def check_out(array):
    out = True
    non_zero = 0
    for i in range(4):
        if 0 not in array[i]:
            non_zero += 1
    if non_zero >= 4:
        for i in range(4):
            for ii in range(4):
                if ii != 3 and array[i][ii] == array[i][ii+1] and out == True:
                    out = False
                if  i != 3 and array[i][ii] == array[i + 1][ii] and out == True:
                    out = False
                    return out
        if out == True:
            pygame.display.set_caption("YOU LOSE ! YOU GOO!!!!")
            pygame.time.wait(2000)
            sys.exit()
flag = True
while flag == True:
    get_board(array)
    pygame.display.update()
    for events in pygame.event.get():
        if events.type == pygame.QUIT:
            sys.exit()
        if events.type == pygame.KEYDOWN:
            if events.key == pygame.K_RIGHT:
                move_right()
                #add_new()
                get_board(array)
                check_win(array)
                check_out(array)
            if events.key == pygame.K_LEFT:
                move_left()
                get_board(array)
                check_win(array)
                check_out(array)

            if events.key == pygame.K_DOWN:
                move_down()
                get_board(array)
                check_win(array)
                check_out(array)
            if events.key == pygame.K_UP:
                move_up()
                get_board(array)
                check_win(array)
                check_out(array)

pygame 2.1.2 (SDL 2.0.18, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [2. 0. 0. 0.]]
