In [ ]:
import numpy as np
import random
import pygame
import sys
pygame.init()
array = np.zeros((6,6))
def create_board():
    for j in range(35):
        j += 1
        done = False
        while done == False:
            y = random.choice([0,1,2,3,4,5])
            x = random.choice([0,1,2,3,4,5])            
            if array[y][x] == 0:
                array[y][x] = j
                done = True
    return array
def move_piece(x_pos,y_pos):
    for c in range(6):
        for r in range(6):
            if array[c][r] == 0:
                y_blank = c
                x_blank = r
    if y_pos - y_blank == 0 and x_pos > x_blank:
        shift = x_blank
        for i in range(x_pos-x_blank):
            i += 1
            array[y_pos][shift] = array[y_pos][x_blank + i]
            shift += 1
            pygame.time.wait(50)
        array[y_pos][x_pos] = 0
    if y_pos - y_blank == 0 and x_pos < x_blank:
        shift = x_blank
        for i in range(x_blank- x_pos):
            i += 1
            array[y_pos][shift] = array[y_pos][x_blank - i]
            shift -= 1
            pygame.time.wait(50)
        array[y_pos][x_pos] = 0
    if x_pos - x_blank == 0 and y_pos > y_blank:
        shift = y_blank
        for i in range(y_pos-y_blank):
            i += 1
            array[shift][x_pos] = array[y_blank + i][x_pos]
            shift += 1
            pygame.time.wait(50)
        array[y_pos][x_pos] = 0
    if x_pos - x_blank == 0 and y_pos < y_blank:
        shift = y_blank
        for i in range(y_blank - y_pos):
            i += 1
            array[shift][x_pos] = array[y_blank - i][x_pos]
            shift -= 1
            pygame.time.wait(50)
        array[y_pos][x_pos] = 0
myfont = pygame.font.SysFont("monospace",50)
def draw_board():
    for i in range(6):
        for ii in range(6):
            if array[i][ii] != 0:
                pygame.draw.rect(wind,(200,125,50),(ii*100,i*100,95,95))
                label = myfont.render(str(int(array[i][ii])),1,(0,0,150))
                wind.blit(label,(ii*100+25,i*100+25))
            else:
                pygame.draw.rect(wind,(101,67,33),(ii*100,i*100,95,95))
    pygame.display.update()
def check_win():
    won = True
    for i in range(6):
        for ii in range(6):
            if (array[i][ii] != i*6 + ii + 1 and i*6 + ii + 1 != 36) or array[5][5] != 0:
                won = False
    if won == True:
        pygame.display.set_caption("WINNER WINNER CHICKEN DINNER")
        pygame.time.wait(2000)
        sys.exit()
create_board()
print(array)
wind = pygame.display.set_mode((600,600))
pygame.display.set_caption("you can interchange two numbers by dragging them(only once)")
gameover = False
exchanged = False
while gameover == False:
    draw_board()
    pygame.display.update()
    for events in pygame.event.get():
        if events.type == pygame.MOUSEBUTTONDOWN:
            x_pos = int(events.pos[0]/100)
            y_pos = int(events.pos[1]/100)
            move_piece(x_pos,y_pos)
            check_win()

pygame 2.1.2 (SDL 2.0.18, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[ 0. 23. 18. 17. 26. 30.]
 [25. 28.  9.  7. 20. 16.]
 [11. 35. 27. 29. 32. 31.]
 [13. 22.  8. 15. 34.  1.]
 [ 6. 19. 24. 33.  5.  4.]
 [10. 21. 14.  2.  3. 12.]]
