In [1]:
import pygame
import sys
import math
import numpy as np
pygame.init()
wind = pygame.display.set_mode((600,600))
array = np.zeros((3,3))
print(array)
def getboard():
    for c in range(3):
        for r in range(3):
            pygame.draw.rect(wind,(255,255,255),(r*200+5,c*200+5,190,190))
    pygame.display.update()

def checkwin(turn,xpos,ypos):
    if array[0][xpos]==turn and array[1][xpos]==turn and array[2][xpos]==turn:
        return True
    if array[ypos][0]==turn and array[ypos][1]==turn and array[ypos][2]==turn:
        return True
    if array[0][0]==turn and array[1][1]==turn and array[2][2]==turn:
        return True
    if array[2][0]==turn and array[1][1]==turn and array[0][2]==turn:
        return True
    pygame.display.update()
        
        
getboard()
myfont = pygame.font.SysFont("monospace",150)
gameover = False
turn = 1
pygame.display.set_caption("PLAYER 1 TURN")
while not gameover:
    pygame.display.update()
    for events in pygame.event.get():
        if events.type == pygame.QUIT:
            sys.exit()
        if events.type == pygame.MOUSEBUTTONDOWN:
            xpos = int(math.floor(events.pos[0]/200))
            ypos = int(math.floor(events.pos[1]/200))
            if array[ypos][xpos] == 0:
                if turn == 1:
                    label = myfont.render("O",1,(255,0,0))
                    array[ypos][xpos] = 1
                else:
                    label = myfont.render("X",1,(255,0,0))
                    array[ypos][xpos] = -1
                wind.blit(label,(xpos*200+55,ypos*200+20))
                pygame.display.update()
                gameover = checkwin(turn,xpos,ypos)
                if gameover:
                    pygame.display.set_caption("PLAYER {} WINS".format(int((turn-3)/(-2))))
                    sys.exit()
                turn*=-1
                pygame.display.set_caption("PLAYER {} TURN".format(int((turn-3)/(-2))))

pygame 2.1.2 (SDL 2.0.18, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


SystemExit: 

C:\Users\Vishesh\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
