In [ ]:
import pygame
import numpy as np
import sys
pygame.init()
wind = pygame.display.set_mode((700,700))
pygame.Surface.fill(wind,(0,0,0))
arr = np.array([[0,-1,0,-1,0,-1,0,-1,0,-1],[-1,0,-1,0,-1,0,-1,0,-1,0],[0,-1,0,-1,0,-1,0,-1,0,-1],[-1,0,-1,0,-1,0,-1,0,-1,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,1,0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0,1,0]])
print(arr)
def initiate_board():
    for i in range(10):
        for j in range(10):
            if (i+j)%2==0:
                pygame.draw.rect(wind,(222,184,135),(j*70,i*70,70,70))
            else:
                pygame.draw.rect(wind,(160,82,45),(j*70,i*70,70,70))
                
            if arr[i][j] == 1:
                pygame.draw.circle(wind,(255,255,255),(j*70+35,i*70+35),32)
            elif arr[i][j] == -1:
                pygame.draw.circle(wind,(0,0,0),(j*70+35,i*70+35),32)
            elif arr[i][j] == 2 or arr[i][j]==-2:
                if arr[i][j]==2:
                    pygame.draw.circle(wind,(255,255,255),(j*70+35,i*70+35),32)
                else:
                    pygame.draw.circle(wind,(0,0,0),(j*70+35,i*70+35),32)
                pygame.draw.circle(wind,(255,215,0),(j*70+35,i*70+35),20)
    pygame.display.update()


def max_moves_man(arr,xpos,ypos,turn):
    maxm = 0
    maxmpath = [[]]
    if xpos<8 and ypos<8:
        if arr[ypos+1][xpos+1]*turn<0 and arr[ypos+2][xpos+2]==0:
            k = arr[ypos+1][xpos+1]
            arr[ypos+1][xpos+1] = 0
            mm,mmpath = max_moves_man(arr,xpos+2,ypos+2,turn)
            mm+=1
            arr[ypos+1][xpos+1] = k
            if mm>maxm:
                maxm = mm
                maxmpath = mmpath
            elif mm==maxm:
                maxmpath+= mmpath
    if xpos<8 and ypos>1:
        if arr[ypos-1][xpos+1]*turn < 0 and arr[ypos-2][xpos+2]==0:
            k = arr[ypos-1][xpos+1]
            arr[ypos-1][xpos+1] = 0
            mm,mmpath = max_moves_man(arr,xpos+2,ypos-2,turn)
            mm+=1
            arr[ypos-1][xpos+1] = k
            if mm>maxm:
                maxm = mm
                maxmpath = mmpath
            elif mm==maxm:
                maxmpath+= mmpath
    if xpos>1 and ypos>1:
        if arr[ypos-1][xpos-1]*turn < 0 and arr[ypos-2][xpos-2]==0:
            k = arr[ypos-1][xpos-1]
            arr[ypos-1][xpos-1] = 0
            mm,mmpath = max_moves_man(arr,xpos-2,ypos-2,turn)
            mm+=1
            arr[ypos-1][xpos-1] = k
            if mm>maxm:
                maxm = mm
                maxmpath = mmpath
            elif mm==maxm:
                maxmpath+= mmpath
    if xpos>1 and ypos<8:
        if arr[ypos+1][xpos-1]*turn<0 and arr[ypos+2][xpos-2]==0:
            k = arr[ypos+1][xpos-1]
            arr[ypos+1][xpos-1] = 0
            mm,mmpath = max_moves_man(arr,xpos-2,ypos+2,turn)
            mm+=1
            arr[ypos+1][xpos-1] = k
            if mm>maxm:
                maxm = mm
                maxmpath = mmpath
            elif mm==maxm:
                maxmpath+= mmpath
    for i in range(len(maxmpath)):
        maxmpath[i].append((xpos,ypos))
    return maxm,maxmpath

def max_moves_king(arr,xpos, ypos, turn):
    knot = arr[ypos][xpos]
    arr[ypos][xpos] = 0
    maxm = 0
    maxmpath = [[]]
    
    i,j = ypos-1,xpos-1
    while (i>0 and j>0):
        if arr[i][j]*turn>0:
            break
        elif arr[i][j]==0:
            i-=1
            j-=1
        else:
            inot = i
            jnot = j
            k = arr[inot][jnot]
            arr[inot][jnot] = 0
            while (i>0 and j>0):
                i-=1
                j-=1
                if arr[i][j]==0:
                    mm, mmpath = max_moves_king(arr,j,i,turn)
                    mm+=1
                    if mm>maxm:
                        maxm = mm
                        maxmpath = mmpath
                    elif mm==maxm:
                        maxmpath+= mmpath
                else:
                    break
            arr[inot][jnot] = k
            break
    i,j = ypos+1,xpos+1
    while (i<9 and j<9):
        if arr[i][j]*turn>0:
            break
        elif arr[i][j]==0:
            i+=1
            j+=1
        else:
            inot = i
            jnot = j
            k = arr[inot][jnot]
            arr[inot][jnot] = 0
            while (i<9 and j<9):
                i+=1
                j+=1
                if arr[i][j]==0:
                    mm, mmpath = max_moves_king(arr,j,i,turn)
                    mm+=1
                    if mm>maxm:
                        maxm = mm
                        maxmpath = mmpath
                    elif mm==maxm:
                        maxmpath+= mmpath
                else:
                    break
            arr[inot][jnot] = k
            break
    i,j = ypos-1,xpos+1
    while (i>0 and j<9):
        if arr[i][j]*turn>0:
            break
        elif arr[i][j]==0:
            i-=1
            j+=1
        else:
            inot = i
            jnot = j
            k = arr[inot][jnot]
            arr[inot][jnot] = 0
            while (i>0 and j<9):
                i-=1
                j+=1
                if arr[i][j]==0:
                    mm, mmpath = max_moves_king(arr,j,i,turn)
                    mm+=1
                    if mm>maxm:
                        maxm = mm
                        maxmpath = mmpath
                    elif mm==maxm:
                        maxmpath+= mmpath
                else:
                    break
            arr[inot][jnot] = k
            break
    i,j = ypos+1,xpos-1
    while (i<9 and j>0):
        if arr[i][j]*turn>0:
            break
        elif arr[i][j]==0:
            i+=1
            j-=1
        else:
            inot = i
            jnot = j
            k = arr[inot][jnot]
            arr[inot][jnot] = 0
            while (i<9 and j>0):
                i+=1
                j-=1
                if arr[i][j]==0:
                    mm, mmpath = max_moves_king(arr,j,i,turn)
                    mm+=1
                    if mm>maxm:
                        maxm = mm
                        maxmpath = mmpath
                    elif mm==maxm:
                        maxmpath+= mmpath
                else:
                    break
            arr[inot][jnot] = k
            break
    for i in range(len(maxmpath)):
        maxmpath[i].append((xpos,ypos))
    arr[ypos][xpos] = knot
    return maxm,maxmpath

def max_moves(turn):
    maxm = 0
    maxmpath = [[]]
    for i in range(10):
        for j in range(10):
            if arr[i][j]==turn:
                mm,mmpath = max_moves_man(arr,j,i,turn)
                if mm>0:
                    if mm>maxm:
                        maxm = mm
                        maxmpath = mmpath
                    elif mm==maxm:
                        maxmpath+=mmpath
            if arr[i][j] == 2*turn:
                mm,mmpath = max_moves_king(arr,j,i,turn)
                if mm>0:
                    if mm>maxm:
                        maxm = mm
                        maxmpath = mmpath
                    elif mm==maxm:
                        maxmpath+=mmpath
    return maxm,maxmpath

def check_move(arr,xpos1, ypos1, xpos2, ypos2, turn):
    if arr[ypos1][xpos1]*turn==1:
        if (xpos2-xpos1==1 or xpos2-xpos1==-1) and ypos2-ypos1==turn*(-1):
            return True
        return False
    if ypos2-ypos1==xpos2-xpos1:
        if xpos2>xpos1:
            for i in range(1,xpos2-xpos1):
                if arr[ypos1+i][xpos1+i]!=0:
                    return False
        else:
            for i in range(1,xpos1-xpos2):
                if arr[ypos1-i][xpos1-i]!=0:
                    return False
    elif ypos2-ypos1 == (-1)*(xpos2-xpos1):
        if xpos2>xpos1:
            for i in range(1,xpos2-xpos1):
                if arr[ypos1-i][xpos1+i]!=0:
                    return False
        else:
            for i in range(1,xpos1-xpos2):
                if arr[ypos1+i][xpos1-i]!=0:
                    return False
    return True

def makeallzero(arr,xpos1,ypos1,xpos2,ypos2):
    if xpos1<xpos2:
        if ypos2>ypos1:
            for i in range(1,xpos2-xpos1):
                if arr[ypos1+i][xpos1+i]!=0:
                    arr[ypos1+i][xpos1+i] = 0
                    break
        else:
            for i in range(1,xpos2-xpos1):
                if arr[ypos1-i][xpos1+i]!=0:
                    arr[ypos1-i][xpos1+i] = 0
                    break
    else:
        if ypos2>ypos1:
            for i in range(1,xpos1-xpos2):
                if arr[ypos1+i][xpos1-i]!=0:
                    arr[ypos1+i][xpos1-i] = 0
                    break
        else:
            for i in range(1,xpos1-xpos2):
                if arr[ypos1-i][xpos1-i]!=0:
                    arr[ypos1-i][xpos1-i] = 0
                    break
    arr[ypos2][xpos2] = arr[ypos1][xpos1]
    arr[ypos1][xpos1] = 0
    return 1

turn = 1
#white has turn 1 and black has turn -1
#white has pieces 1,2 and black has pieces -1,-2
gameover = False
initiate_board()
pygame.display.set_caption("PLAYER {} TURN".format(int((turn-3)/(-2))))
maxm,maxmpath = max_moves(turn)
counter = 0
whitecounter, blackcounter = 20,20
currentpath = []
print(maxm,maxmpath)
while gameover == False:
    pygame.display.update()
    for events in pygame.event.get():
        if events.type == pygame.QUIT:
            sys.exit()
            pygame.quit()
        if maxm==0:
            if events.type == pygame.MOUSEBUTTONDOWN:
                if counter==0:
                    xpos1 = int(events.pos[0]/70)
                    ypos1 = int(events.pos[1]/70)
                    if arr[ypos1][xpos1]*turn>0:
                        counter = 1
                else:
                    xpos2 = int(events.pos[0]/70)
                    ypos2 = int(events.pos[1]/70)
                    if arr[ypos2][xpos2]==0:
                        output = check_move(arr, xpos1,ypos1,xpos2,ypos2,turn)
                        if output:
                            if arr[ypos1][xpos1]==1 and ypos2==0:
                                arr[ypos2][xpos2] = 2
                            elif arr[ypos1][xpos1]==-1 and ypos2==9:
                                arr[ypos2][xpos2] = -2
                            else:
                                arr[ypos2][xpos2] = arr[ypos1][xpos1]
                            arr[ypos1][xpos1] = 0
                            turn*=-1
                            maxm,maxmpath = max_moves(turn)
                            initiate_board()
                            pygame.display.set_caption("PLAYER {} TURN".format(int((turn-3)/(-2))))
                            #gameover = check_win(arr)
                    counter = 0
        else:
            if events.type == pygame.MOUSEBUTTONDOWN:
                xpos1 = int(events.pos[0]/70)
                ypos1 = int(events.pos[1]/70)
                flag = False
                for i in maxmpath:
                    if (currentpath+[(xpos1,ypos1)])[::-1]==i[maxm-counter:]:
                        flag = True
                        break
                if flag==True:
                    if counter>0:
                        makeallzero(arr,currentpath[-1][0],currentpath[-1][1],xpos1,ypos1)
                    initiate_board()
                    currentpath+=[(xpos1,ypos1)]    
                    counter+=1
                    if counter==maxm+1:
                        if turn==1:
                            blackcounter-=maxm
                            if ypos1==0:
                                arr[ypos1][xpos1] = 2
                        else:
                            whitecounter-=maxm
                            if ypos1==7:
                                arr[ypos1][xpos1] = -2
                        turn*=-1
                        pygame.display.set_caption("PLAYER {} TURN".format(int((turn-3)/(-2))))
                        initiate_board()
                        maxm,maxmpath = max_moves(turn)
                        counter = 0
                        currentpath = []
                        if blackcounter==0:
                            pygame.display.set_caption("PLAYER 1 WINS")
                            pygame.display.update()
                            gameover = True
                        elif whitecounter==0:
                            pygame.display.set_caption("PLAYER 2 WINS")
                            pygame.display.update()
                            gameover = True
                        #gameover = check_win(arr)

pygame 2.1.2 (SDL 2.0.18, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[ 0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0]
 [ 0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  1  0  1  0  1  0  1]
 [ 1  0  1  0  1  0  1  0  1  0]
 [ 0  1  0  1  0  1  0  1  0  1]
 [ 1  0  1  0  1  0  1  0  1  0]]
0 [[]]
